on: 
  release:
    types:
      - created

name: ipt2socks
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build ipt2socks Package  
    strategy:
      fail-fast: false
      matrix:
        SDK_URL:
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm47xx/mips74k/openwrt-sdk-18.06.9-bcm47xx-mips74k_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm47xx/generic/openwrt-sdk-18.06.9-bcm47xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm47xx/legacy/openwrt-sdk-18.06.9-bcm47xx-legacy_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm4908/generic/openwrt-sdk-18.06.9-bcm4908-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm63xx/generic/openwrt-sdk-18.06.9-bcm63xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ath79/tiny/openwrt-sdk-18.06.9-ath79-tiny_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ath79/nand/openwrt-sdk-18.06.9-ath79-nand_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ath79/generic/openwrt-sdk-18.06.9-ath79-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm27xx/bcm2708/openwrt-sdk-18.06.9-bcm27xx-bcm2708_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm27xx/bcm2709/openwrt-sdk-18.06.9-bcm27xx-bcm2709_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm27xx/bcm2710/openwrt-sdk-18.06.9-bcm27xx-bcm2710_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm27xx/bcm2711/openwrt-sdk-18.06.9-bcm27xx-bcm2711_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/sunxi/cortexa53/openwrt-sdk-18.06.9-sunxi-cortexa53_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/sunxi/cortexa8/openwrt-sdk-18.06.9-sunxi-cortexa8_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ramips/mt76x8/openwrt-sdk-18.06.9-ramips-mt76x8_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ramips/mt7621/openwrt-sdk-18.06.9-ramips-mt7621_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ramips/mt7620/openwrt-sdk-18.06.9-ramips-mt7620_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ramips/rt305x/openwrt-sdk-18.06.9-ramips-rt305x_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/bcm53xx/generic/openwrt-sdk-18.06.9-bcm53xx-generic_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ipq40xx/generic/openwrt-sdk-18.06.9-ipq40xx-generic_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/ipq806x/generic/openwrt-sdk-18.06.9-ipq806x-generic_gcc-7.3.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/x86/generic/openwrt-sdk-18.06.9-x86-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/x86/64/openwrt-sdk-18.06.9-x86-64_gcc-7.3.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/18.06.9/targets/rockchip/armv8/openwrt-sdk-18.06.9-rockchip-armv8_gcc-7.3.0_musl.Linux-x86_64.tar.xz
    steps:
    
    - name: Checkout - ${{ github.ref }}
      uses: actions/checkout@v1
      
    - name: Install env dependencies
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool libev-dev libc-ares-dev libudns-dev libncurses-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean 
    
    - name: TAG
      run: |
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
          
    - name: Download SDK
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
      run: |
        wget -q "${SDK_URL}"
        tar xJf openwrt-sdk-*.tar.xz -C ../
        mv -f "${GITHUB_WORKSPACE}" ../src
        mv ../openwrt-sdk-* "${GITHUB_WORKSPACE}"
        
    - name: Prepare targets
      env:
        REPF: ${{ github.repository }}
      run: |
        REP=$(basename "${REPF}")
        mv -vf ../src "package/${REP}"
        
    - name: Load custom configuration
      env:
        DEBIAN_FRONTEND: noninteractive
        CONFIG_FILE: '.config'
        REPF: ${{ github.repository }}
      run: |
        REP=$(basename "${REPF}")
        [ -e "package/${REP}/${CONFIG_FILE}" ] && mv "${CONFIG}" .config
        make defconfig
           
    - name: Compile Package
      env:
        DEBIAN_FRONTEND: noninteractive
        PKGN: ${{ 'ipt2socks' }}
      run: |
        make package/${PKGN}/compile -j$(nproc) V=s
        mkdir ../bin
        find bin/ -type f -name "*${PKGN}*" | xargs -t -i mv -vf {} ../bin
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          draft: true
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: ../bin/*.ipk
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
